version: '3'
services:
  laboratoire:
    build:
      dockerfile: DockerfileLab
    ports:
      - 80
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - eleve1
  pirate:
    build:
      dockerfile: DockerfilePirate
    ports:
      - 22
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - eleve1

networks:
  eleve1:

